language: node_js
node_js:
  - "6.9"
  - "10.1"
sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - npm install
  - npm build
