export const DEMO_COUNTER_PLUS_ONE = 'DEMO_COUNTER_PLUS_ONE';
export const DEMO_COUNTER_MINUS_ONE = 'DEMO_COUNTER_MINUS_ONE';
export const DEMO_FETCH_REDDIT_LIST_BEGIN = 'DEMO_FETCH_REDDIT_LIST_BEGIN';
export const DEMO_FETCH_REDDIT_LIST_SUCCESS = 'DEMO_FETCH_REDDIT_LIST_SUCCESS';
export const DEMO_FETCH_REDDIT_LIST_FAILURE = 'DEMO_FETCH_REDDIT_LIST_FAILURE';
export const DEMO_FETCH_REDDIT_LIST_DISMISS_ERROR = 'DEMO_FETCH_REDDIT_LIST_DISMISS_ERROR';
